site_name: RAYLIB projects
plugins:
  - search
  - mkdocstrings
theme:
  name: material
  nav:
  - overview: index.md
  - simple window: simple_window.md
  - moving ball: moving_ball.md
  - 3D cube: 3d_rotating_cube.md
  - 3D collions check: 3d_collisions_check.md
  - Instantiate Object: instantiate_rings.md
  - solar system: solar_system.md
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
  &copy; 2026 <a href="https://github.com/jonathanbouchet"  target="_blank" rel="noopener">Jonathan Bouchet</a>